export const CHARACTERS_UPDATE_LIST = 'CHARACTERS_UPDATE_LIST';
export const CHARACTERS_UPDATE_FETCHING = 'CHARACTERS_UPDATE_FETCHING';
export const CHARACTERS_UPDATE_OFFSET = 'CHARACTERS_UPDATE_OFFSET';
export const CHARACTERS_UPDATE_COMIC_LIST = 'CHARACTERS_UPDATE_COMIC_LIST';